[build]
  command = "yarn build && yarn build:lambda"
  functions = "lambda"
  publish = "build"

[template.environment]
  API_KEY = "keyvjbVyJKBdcU2qR"
  REACT_APP_AIRTABLE_BASE_ID = "app2OQ52OpAEK5GoV"
